### ISSUE TITLE
Can you give more simple example using npm ? please 

### ISSUE THREAD

**Issue by dolev146** [sarpere/heatmapjs-react#12]
i need an example of simple reactjs app

with the data = [
{
x: 1,
y:2,
value : 3
},

{
x: 2,
y:4,
value : 3
}

 
]

**Comment by sarpere** [comment]
Hi @dolev146 ,

You can find an example [here](https://github.com/sarpere/heatmapjs-react/tree/master/example). Its basically simple setup with Vite, reactJs and Ts.

https://github.com/sarpere/heatmapjs-react/tree/master/example
If you want more example, take a look at storybook.
